// <auto-generated />
using System;
using ContaRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ContaRepository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ContaDomain.Entities.Conta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dataLeitura");

                    b.Property<DateTime>("dataPagamento");

                    b.Property<int?>("imovelid");

                    b.Property<double>("mediaConsumo");

                    b.Property<double>("numeroLeitura");

                    b.Property<double>("qtdKw");

                    b.Property<double>("valorConta");

                    b.HasKey("id");

                    b.HasIndex("imovelid");

                    b.ToTable("contas");
                });

            modelBuilder.Entity("ContaDomain.Entities.Imovel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro");

                    b.Property<string>("Cidade");

                    b.Property<string>("Estado");

                    b.Property<string>("Identificacao");

                    b.Property<string>("Numero");

                    b.HasKey("id");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("ContaDomain.Entities.Conta", b =>
                {
                    b.HasOne("ContaDomain.Entities.Imovel", "imovel")
                        .WithMany("contas")
                        .HasForeignKey("imovelid");
                });
#pragma warning restore 612, 618
        }
    }
}
